/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
rule "Rule 151"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 151");
end
rule "Rule 152"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 152");
end
rule "Rule 153"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 153");
end
rule "Rule 154"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 154");
end
rule "Rule 155"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 155");
end
rule "Rule 156"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 156");
end
rule "Rule 157"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 157");
end
rule "Rule 158"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 158");
end
rule "Rule 159"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 159");
end
rule "Rule 160"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 160");
end
rule "Rule 161"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 161");
end
rule "Rule 162"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 162");
end
rule "Rule 163"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 163");
end
rule "Rule 164"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 164");
end
rule "Rule 165"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 165");
end
rule "Rule 166"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 166");
end
rule "Rule 167"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 167");
end
rule "Rule 168"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 168");
end
rule "Rule 169"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 169");
end
rule "Rule 170"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 170");
end
rule "Rule 171"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 171");
end
rule "Rule 172"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 172");
end
rule "Rule 173"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 173");
end
rule "Rule 174"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 174");
end
rule "Rule 175"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 175");
end
rule "Rule 176"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 176");
end
rule "Rule 177"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 177");
end
rule "Rule 178"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 178");
end
rule "Rule 179"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 179");
end
rule "Rule 180"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 180");
end
rule "Rule 181"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 181");
end
rule "Rule 182"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 182");
end
rule "Rule 183"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 183");
end
rule "Rule 184"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 184");
end
rule "Rule 185"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 185");
end
rule "Rule 186"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 186");
end
rule "Rule 187"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 187");
end
rule "Rule 188"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 188");
end
rule "Rule 189"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 189");
end
rule "Rule 190"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 190");
end
rule "Rule 191"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 191");
end
rule "Rule 192"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 192");
end
rule "Rule 193"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 193");
end
rule "Rule 194"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 194");
end
rule "Rule 195"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 195");
end
rule "Rule 196"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 196");
end
rule "Rule 197"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 197");
end
rule "Rule 198"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 198");
end
rule "Rule 199"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 199");
end
rule "Rule 200"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 200");
end
rule "Rule 201"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 201");
end
rule "Rule 202"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 202");
end
rule "Rule 203"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 203");
end
rule "Rule 204"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 204");
end
rule "Rule 205"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 205");
end
rule "Rule 206"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 206");
end
rule "Rule 207"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 207");
end
rule "Rule 208"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 208");
end
rule "Rule 209"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 209");
end
rule "Rule 210"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 210");
end
rule "Rule 211"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 211");
end
rule "Rule 212"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 212");
end
rule "Rule 213"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 213");
end
rule "Rule 214"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 214");
end
rule "Rule 215"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 215");
end
rule "Rule 216"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 216");
end
rule "Rule 217"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 217");
end
rule "Rule 218"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 218");
end
rule "Rule 219"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 219");
end
rule "Rule 220"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 220");
end
rule "Rule 221"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 221");
end
rule "Rule 222"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 222");
end
rule "Rule 223"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 223");
end
rule "Rule 224"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 224");
end
rule "Rule 225"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 225");
end
