rule "Rule 76"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 76");
end
rule "Rule 77"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 77");
end
rule "Rule 78"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 78");
end
rule "Rule 79"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 79");
end
rule "Rule 80"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 80");
end
rule "Rule 81"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 81");
end
rule "Rule 82"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 82");
end
rule "Rule 83"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 83");
end
rule "Rule 84"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 84");
end
rule "Rule 85"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 85");
end
rule "Rule 86"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 86");
end
rule "Rule 87"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 87");
end
rule "Rule 88"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 88");
end
rule "Rule 89"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 89");
end
rule "Rule 90"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 90");
end
rule "Rule 91"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 91");
end
rule "Rule 92"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 92");
end
rule "Rule 93"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 93");
end
rule "Rule 94"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 94");
end
rule "Rule 95"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 95");
end
rule "Rule 96"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 96");
end
rule "Rule 97"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 97");
end
rule "Rule 98"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 98");
end
rule "Rule 99"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 99");
end
rule "Rule 100"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 100");
end
rule "Rule 101"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 101");
end
rule "Rule 102"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 102");
end
rule "Rule 103"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 103");
end
rule "Rule 104"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 104");
end
rule "Rule 105"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 105");
end
rule "Rule 106"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 106");
end
rule "Rule 107"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 107");
end
rule "Rule 108"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 108");
end
rule "Rule 109"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 109");
end
rule "Rule 110"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 110");
end
rule "Rule 111"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 111");
end
rule "Rule 112"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 112");
end
rule "Rule 113"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 113");
end
rule "Rule 114"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 114");
end
rule "Rule 115"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 115");
end
rule "Rule 116"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 116");
end
rule "Rule 117"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 117");
end
rule "Rule 118"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 118");
end
rule "Rule 119"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 119");
end
rule "Rule 120"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 120");
end
rule "Rule 121"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 121");
end
rule "Rule 122"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 122");
end
rule "Rule 123"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 123");
end
rule "Rule 124"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 124");
end
rule "Rule 125"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 125");
end
rule "Rule 126"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 126");
end
rule "Rule 127"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 127");
end
rule "Rule 128"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 128");
end
rule "Rule 129"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 129");
end
rule "Rule 130"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 130");
end
rule "Rule 131"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 131");
end
rule "Rule 132"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 132");
end
rule "Rule 133"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 133");
end
rule "Rule 134"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 134");
end
rule "Rule 135"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 135");
end
rule "Rule 136"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 136");
end
rule "Rule 137"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 137");
end
rule "Rule 138"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 138");
end
rule "Rule 139"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 139");
end
rule "Rule 140"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 140");
end
rule "Rule 141"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 141");
end
rule "Rule 142"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 142");
end
rule "Rule 143"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 143");
end
rule "Rule 144"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 144");
end
rule "Rule 145"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 145");
end
rule "Rule 146"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 146");
end
rule "Rule 147"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 147");
end
rule "Rule 148"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 148");
end
rule "Rule 149"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 149");
end
rule "Rule 150"
ruleflow-group "gather ingredients" 
no-loop
when
	Object()
then
	System.out.println("rule 150");
end
